# Generated by Django 3.2.9 on 2021-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletype',
            old_name='img_url',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(auto_created=200),
        ),
    ]
