# Generated by Django 3.2.9 on 2021-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211207_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletype',
            name='img',
            field=models.CharField(max_length=30),
        ),
    ]
