# Generated by Django 3.2.9 on 2021-12-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profiletype_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
