# Generated by Django 3.2.9 on 2021-12-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='points',
            new_name='coins',
        ),
    ]
