# Generated by Django 3.2.9 on 2021-12-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dino_rarity_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dino',
            name='rarity_rate',
            field=models.PositiveIntegerField(choices=[(200, 'Common'), (500, 'Medium'), (800, 'Rare'), (1000, 'Very Rare')]),
        ),
    ]
