# Generated by Django 3.2.9 on 2021-12-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dino_rarity_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('rarity_rate', models.PositiveIntegerField(choices=[(200, 'D'), (500, 'C'), (800, 'B'), (1000, 'A')])),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='cards', to='main.Card'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card'),
        ),
        migrations.DeleteModel(
            name='Dino',
        ),
    ]
