# Generated by Django 3.2.9 on 2021-12-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211210_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
