# Generated by Django 3.2.9 on 2021-12-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_open',
        ),
    ]
