# Generated by Django 3.2.9 on 2021-12-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_transaction_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
