# Generated by Django 3.2.9 on 2021-12-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
