# Generated by Django 3.2.9 on 2021-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.URLField(),
        ),
    ]
